
runtime: nodejs16
service: qa-env
env: flex
automatic_scaling:
   min_num_instances: 1
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: dist/\1
  upload: dist/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
